# Generated by Django 3.0.8 on 2020-09-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dhcp',
            fields=[
                ('id_prefixes', models.IntegerField(primary_key=True, serialize=False)),
                ('prefixes', models.GenericIPAddressField()),
                ('netmask', models.GenericIPAddressField()),
                ('id_domain', models.IntegerField()),
                ('gateway', models.GenericIPAddressField()),
                ('opcao', models.IntegerField()),
                ('tipo', models.CharField(max_length=4)),
                ('ip_inicial', models.GenericIPAddressField()),
                ('ip_final', models.GenericIPAddressField()),
                ('data_criacao', models.DateTimeField()),
                ('id_resp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to='dhcpd.Dhcp')),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='dhcpd.Dhcp')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id_resp', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id_servico', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=7)),
                ('port_number', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ipfixo',
            fields=[
                ('id_ipfixo', models.IntegerField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=16)),
                ('ip_host', models.GenericIPAddressField()),
                ('host', models.CharField(max_length=20)),
                ('defaultleasetime', models.IntegerField()),
                ('maxleasetime', models.IntegerField()),
                ('id_prefixes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcpd.Dhcp')),
            ],
        ),
    ]
