# Generated by Django 3.1 on 2020-11-06 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dhcp',
            fields=[
                ('id_prefixes', models.AutoField(primary_key=True, serialize=False)),
                ('prefixes', models.GenericIPAddressField()),
                ('netmask', models.GenericIPAddressField()),
                ('id_domain', models.IntegerField()),
                ('gateway', models.GenericIPAddressField()),
                ('option', models.CharField(default='43', max_length=2)),
                ('tipo', models.CharField(default='IPV4', max_length=9)),
                ('ip_inicial', models.GenericIPAddressField()),
                ('ip_final', models.GenericIPAddressField()),
                ('defaultleasetime', models.IntegerField(default=None)),
                ('maxleasetime', models.IntegerField(default=None)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2020, 11, 6, 23, 11, 47, 473014, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id_resp', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=7)),
                ('port_number', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ipfixo',
            fields=[
                ('id_ipfixo', models.AutoField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_host', models.GenericIPAddressField()),
                ('host', models.CharField(max_length=20)),
                ('id_prefixes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dhcp.dhcp')),
            ],
        ),
        migrations.AddField(
            model_name='dhcp',
            name='id_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dhcp.responsavel'),
        ),
        migrations.AddField(
            model_name='dhcp',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dhcp.servico'),
        ),
    ]
