# Generated by Django 3.0.8 on 2020-09-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='id_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcpd.Servicos'),
        ),
    ]
