# Generated by Django 3.1 on 2020-12-01 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 19, 50, 1, 823557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='prefix',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.prefix'),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.vlan'),
        ),
    ]
