# Generated by Django 3.1 on 2020-11-06 23:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0002_auto_20201106_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 23, 28, 4, 821087, tzinfo=utc)),
        ),
    ]
