# Generated by Django 3.1 on 2020-12-01 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0002_auto_20201201_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 22, 8, 13, 579374, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='defaultleasetime',
            field=models.IntegerField(default=86400),
        ),
    ]
