# Generated by Django 3.1 on 2020-12-01 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0003_auto_20201201_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp',
            name='dns_1',
            field=models.CharField(default='10.3.156.40', max_length=15),
        ),
        migrations.AddField(
            model_name='dhcp',
            name='dns_2',
            field=models.CharField(default='10.3.156.41', max_length=15),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 23, 15, 54, 693338, tzinfo=utc)),
        ),
    ]
