# Generated by Django 3.0.8 on 2020-09-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0003_auto_20200909_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
    ]
