# Generated by Django 3.1 on 2020-11-10 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0003_auto_20201106_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp',
            name='prefix',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.prefix'),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 11, 22, 46, 78377, tzinfo=utc)),
        ),
    ]
