# Generated by Django 3.1 on 2020-11-04 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0003_auto_20201104_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 18, 32, 54, 411753)),
        ),
    ]
