# Generated by Django 3.1 on 2020-12-01 23:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0004_add_field_dns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 23, 18, 8, 409790, tzinfo=utc)),
        ),
    ]
