# Generated by Django 3.1 on 2020-11-04 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0004_auto_20201104_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipfixo',
            old_name='mac',
            new_name='mac_address',
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 18, 51, 53, 195403)),
        ),
    ]
