# Generated by Django 3.1 on 2020-11-10 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_standardize_description'),
        ('dhcp', '0004_auto_20201110_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='name',
            field=models.OneToOneField(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 11, 53, 34, 300480, tzinfo=utc)),
        ),
    ]
