# Generated by Django 3.0.8 on 2020-09-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0005_auto_20200916_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipfixo',
            name='mac',
            field=models.CharField(max_length=17),
        ),
    ]
