# Generated by Django 3.0.8 on 2020-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0006_auto_20200916_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='tipo',
            field=models.CharField(default='IPV4/IPV6', max_length=9),
        ),
    ]
