# Generated by Django 3.0.8 on 2020-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0007_auto_20200918_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcp',
            options={'ordering': ['id_prefixes'], 'verbose_name': 'id', 'verbose_name_plural': 'Id Prefixes'},
        ),
    ]
