# Generated by Django 3.0.8 on 2020-09-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0008_auto_20200930_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcp',
            options={},
        ),
    ]
