# Generated by Django 3.0.8 on 2020-09-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0009_auto_20200930_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcp',
            options={'ordering': ['id_prefixes'], 'verbose_name': 'id', 'verbose_name_plural': 'Id Prefixes'},
        ),
    ]
