# Generated by Django 3.0.8 on 2020-09-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0010_auto_20200930_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcp',
            options={},
        ),
    ]
