# Generated by Django 3.0.8 on 2020-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0011_auto_20200930_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='opcao',
            field=models.IntegerField(default='43', max_length=2),
        ),
    ]
