# Generated by Django 3.0.8 on 2020-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpd', '0012_auto_20200930_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='opcao',
            field=models.CharField(default='43', max_length=2),
        ),
    ]
