# Generated by Django 3.1 on 2020-11-11 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0020_auto_20201110_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcp',
            name='netmask',
        ),
        migrations.RemoveField(
            model_name='dhcp',
            name='prefixes',
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 12, 32, 11, 635958, tzinfo=utc)),
        ),
    ]
