# Generated by Django 3.1 on 2020-11-11 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0021_auto_20201111_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 12, 47, 41, 640656, tzinfo=utc)),
        ),
    ]
