# Generated by Django 3.1 on 2020-11-11 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0022_auto_20201111_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 12, 58, 59, 784645, tzinfo=utc)),
        ),
    ]
