# Generated by Django 3.1 on 2020-11-11 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0024_auto_20201111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 19, 12, 23, 83835, tzinfo=utc)),
        ),
    ]
