# Generated by Django 3.1 on 2020-11-11 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0025_auto_20201111_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 19, 22, 45, 492867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='dns_name',
            field=models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.ipaddress'),
        ),
    ]
