# Generated by Django 3.1 on 2020-11-11 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0028_auto_20201111_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 19, 37, 55, 423480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='dns_name',
            field=models.OneToOneField(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='ipaddresses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
    ]
