# Generated by Django 3.1 on 2020-11-11 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0029_auto_20201111_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcp',
            name='dns_name',
        ),
        migrations.AddField(
            model_name='dhcp',
            name='id_domain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 25, 13, 932314, tzinfo=utc)),
        ),
    ]
