# Generated by Django 3.1 on 2020-11-11 21:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0031_auto_20201111_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 45, 32, 637430, tzinfo=utc)),
        ),
    ]
