# Generated by Django 3.1 on 2020-11-11 23:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0034_auto_20201111_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 23, 29, 44, 788264, tzinfo=utc)),
        ),
    ]
