# Generated by Django 3.1 on 2020-11-12 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0041_auto_20201112_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 1, 8, 634905, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='dhcp',
            name='ipaddresses',
        ),
        migrations.AddField(
            model_name='dhcp',
            name='ipaddresses',
            field=models.ManyToManyField(blank=True, null=True, related_name='_dhcp_ipaddresses_+', to='ipam.IPAddress'),
        ),
    ]
