# Generated by Django 3.1 on 2020-11-12 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0042_auto_20201112_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 9, 31, 993925, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='dhcp',
            name='ipaddresses',
        ),
        migrations.AddField(
            model_name='dhcp',
            name='ipaddresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
    ]
