# Generated by Django 3.1 on 2020-11-12 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0043_auto_20201112_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipfixo',
            name='id_prefixes',
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 17, 41, 172569, tzinfo=utc)),
        ),
    ]
