# Generated by Django 3.1 on 2020-11-12 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0045_auto_20201112_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 14, 33, 48, 544130, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ipfixo',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
