# Generated by Django 3.1 on 2020-11-12 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0047_auto_20201112_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 17, 5, 50, 958086, tzinfo=utc)),
        ),
    ]
