# Generated by Django 3.1 on 2020-11-12 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0048_auto_20201112_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 6, 58, 328007, tzinfo=utc)),
        ),
    ]
