# Generated by Django 3.1 on 2020-11-12 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0053_auto_20201112_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 22, 12, 24, 909012, tzinfo=utc)),
        ),
    ]
