# Generated by Django 3.1 on 2020-11-13 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0062_auto_20201113_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipfixo',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.vlan'),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 20, 48, 6, 892303, tzinfo=utc)),
        ),
    ]
