# Generated by Django 3.1 on 2020-11-13 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0065_auto_20201113_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 21, 19, 36, 90106, tzinfo=utc)),
        ),
    ]
