# Generated by Django 3.1 on 2020-11-13 23:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0116_rearport_max_positions'),
        ('dhcp', '0067_auto_20201113_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcp',
            name='local',
        ),
        migrations.AddField(
            model_name='dhcp',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 23, 31, 38, 719135, tzinfo=utc)),
        ),
    ]
