# Generated by Django 3.1 on 2020-11-17 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0069_auto_20201114_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 17, 10, 9, 933950, tzinfo=utc)),
        ),
    ]
