# Generated by Django 3.1 on 2020-11-20 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('dhcp', '0071_auto_20201119_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 11, 52, 21, 517704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.prefix'),
        ),
    ]
