# Generated by Django 3.1 on 2020-11-20 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0075_auto_20201120_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 4, 47, 636739, tzinfo=utc)),
        ),
    ]
