# Generated by Django 3.1 on 2020-11-20 23:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0076_auto_20201120_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 23, 39, 10, 983089, tzinfo=utc)),
        ),
    ]
