# Generated by Django 3.1 on 2020-11-21 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0077_auto_20201120_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 11, 17, 8, 581333, tzinfo=utc)),
        ),
    ]
