# Generated by Django 3.1 on 2020-11-23 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0078_auto_20201121_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcp',
            name='id_resp',
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 20, 42, 50, 324303, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
