# Generated by Django 3.1 on 2020-11-23 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0080_auto_20201123_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 23, 7, 23, 708530, tzinfo=utc)),
        ),
    ]
