# Generated by Django 3.1 on 2020-11-24 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0081_auto_20201123_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp',
            name='is_sinfo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 11, 2, 10, 131623, tzinfo=utc)),
        ),
    ]
