# Generated by Django 3.1 on 2020-11-24 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sdns', '0001_initial'),
        ('dhcp', '0083_auto_20201124_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 13, 42, 3, 415679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='id_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sdns.domain'),
        ),
    ]
