# Generated by Django 3.1 on 2020-11-24 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0084_add_sdns_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 23, 19, 49, 768289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ipfixo',
            name='mac_address',
            field=models.CharField(max_length=41),
        ),
        migrations.AddConstraint(
            model_name='ipfixo',
            constraint=models.UniqueConstraint(fields=('prefix', 'mac_address'), name='unique_Mac_address'),
        ),
    ]
